version: '3'

services:
  api-catalog-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker123
      - POSTGRESQL_DATABASE=apicatalog